project:
  type: website

website:
  title: "Aaron Graybill"
  site-url: "https://www.aarongraybill.com"
  description: "Information and content from Aaron Graybill"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: mini_projects/index.qmd
      text: Mini Projects
    - href: cv/index.qmd
      text: CV
  google-analytics: "G-9E0WQEN2SV"
  favicon: assets/favicon.png

format:
  html:
    highlight-style: a11y
    theme:
      light: 
        - flatly
        - custom.scss
    include-in-header: 
    - text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      #dark: 
      #  - darkly
      #  - custom.css
    toc: true
