project:
  type: website

website:
  title: "Aaron Graybill"
  navbar:
   # left:
   #   - href: index.qmd
   #     text: Home
   #   - href: cv.qmd
   #     text: CV

format:
  html:
    highlight-style: a11y
    theme:
      light: 
        - flatly
        - custom.scss
      #dark: 
      #  - darkly
      #  - custom.css
    toc: true

