project:
  type: website
  pre-render:
    - bash build-cv.sh
  resources:
    - Graybill_CV.pdf

website:
  title: "Aaron Graybill"
  site-url: "https://www.aarongraybill.com"
  description: "Information and content from Aaron Graybill"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: Graybill_CV.pdf
      text: CV
  google-analytics: "G-9E0WQEN2SV"
  favicon: favicon.ico
  repo-url: https://github.com/aarongraybill/personal_website
  repo-actions: source

format:
  html:
    highlight-style: a11y
    theme:
      light: 
        - flatly
        - custom.scss
    include-in-header: 
    - text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    - file: header.html
    toc: true
