project:
  type: website
  pre-render:
    - bash build-cv.sh
  resources:
    - Graybill_CV.pdf

website:
  title: "Aaron Graybill"
  site-url: "https://www.aarongraybill.com"
  description: "Information and content from Aaron Graybill"
  navbar:
    pinned: true
    left:
    - href: index.qmd
      text: Home
    - href: Graybill_CV.pdf
      text: CV
  google-analytics: "G-9E0WQEN2SV"
  favicon: favicon.ico
  image: assets/opengraph.png
  image-alt: "Aaron Graybill with an introduction over a blue and green batik-inspired redwood design."
  open-graph:
    image-width: 1200
    image-height: 630
  twitter-card:
    card-style: summary_large_image
    image-width: 1200
    image-height: 630

format:
  html:
    highlight-style: a11y
    theme:
      light: 
        - flatly
        - custom.scss
    include-in-header: 
    - text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    toc: true
