---
title: Aaron Graybill
date-modified: last-modified
execute: 
  freeze: auto
format:
  html: 
    email-obfuscation: references
  pdf:
    output-file: 'graybill_aaron_cv'
    output-ext: 'pdf'
    include-in-header:
      text: |
        % make horizontal line full width
        \let\oldrule=\rule
        \renewcommand{\rule}[1]{\oldrule{\linewidth}}
        % allow for text justification in multiple columns
        \usepackage{ragged2e}
      
---

```{r}
#| include: false
invisible(2+2)
```

:::: {layout="[[50,-2,50]]" layout-valign="center"}

::: {.cv-left}
<!--
Here the RaggedRight is only used in PDF output, in which
case it's used to correctly left and right align the columns.
RaggedRight means the right is ragged, and the left is straight,
ie left alignment
-->
\RaggedRight 

Aaron Graybill <br>\newline
Research Department <br>\newline
Federal Reserve Bank of Philadelphia <br>\newline
Ten Independence Mall, PA 19106

:::

::: {.cv-right}
<!--
When the left is ragged, the right must be straight,
ie, right aligntment.
-->
\RaggedLeft 

Email: aarongraybill12[at]gmail[dot]com
:::

::::


# Education

-------------

### University of Pennsylvania
:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Non-matriculated Graduate Student
\newline <!--LaTeX needs explicit newline here -->
*Philadelphia, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft Sep. 2023--Present
:::

::::

**Relevant Coursework:**

PhD Microeconomics, Algorithmic Game Theory

### Haverford College

:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight B.A. Economics, High Honors, Magna Cum Laude
\newline
*Haverford, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft  

2018--2022
:::

::::

**Relevant Coursework:**

Advanced Microeconomics, Mathematical Economics, Quantitative Economics, Thesis

\newpage

### Bryn Mawr College

:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight B.A. Mathematics, Dual degree with above
\newline

*Bryn Mawr, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft 

2018--2022
:::

::::

**Relevant Coursework:**

Analysis, Linear Algebra, Stochastic and Numerical Methods, Quantitative Finance, Probability, Applied Multivariate Statistical Analysis

# Professional Experience

---

### Research Analyst
:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Federal Reserve Bank of Philadelphia
\newline
*Philadelphia, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft 

Jun. 2022--Present
:::

::::
- Developed novel methodology to uniquely identify homeowners between properties using co-ownership record and mailing address history
- Leveraged concepts from network theory and linear algebra to convert methodology into optimized algorithms
- Authored more than 5,000 lines of  R code to apply algorithms to hundreds of gigabytes of property-level tax assessment and transaction data
- Automated chart production for Monetary Policy briefings
- Modernized internal data collection and processing by scraping available data, removing reliance on 3rd party vendors


### Teaching Assistant

:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Economics Department, Haverford College
\newline
*Haverford, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft Jan. 2023--May 2023
:::

::::

- Lead problem solving sessions for Advanced Microeconomics, the terminal microeconomics course
- Adapted to student needs, teaching concepts from probability theory, calculus, and intermediate microeconomics


### Research Intern
:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Federal Reserve Bank of Philadelphia
\newline
*Philadelphia, Pennsylvania (Remote)*
:::

::: {.cv-right}
\RaggedLeft Jun. 2020--May. 2022
:::

::::

- Analyzed survey results from the Manufacturing Business Outlook Survey for publication of monthly reports about the local business climate
- Generated a dashboard of statistics and charts for COVID-19’s economic impacts

### Teaching Assistant

:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Economics Department, Haverford College
\newline
*Haverford, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft Sep. 2021--Dec. 2021
:::

::::

- Answered student questions about econometrics
- Graded problem sets and provided constructive commentary


### Economics Question Center Tutor

:::: {layout="[[50,-2,50]]"}

::: {.cv-left}
\RaggedRight Economics Department, Haverford College
\newline
*Haverford, Pennsylvania*
:::

::: {.cv-right}
\RaggedLeft Feb. 2020--May 2022
:::

::::

- Selected to be one of first tutors to set up the Economics Question Center
- Facilitated student collaboration on problem sets and answered questions for all courses

# Awards

---

### Michael M. Weinstein Prize in Economics

*Haverford College, May 2022.*

For having made the greatest overall contribution to departmental life. Awarded for contributions in class, with peers, and for starting the widely used Economics Question Center.

### Runner-Up, Holland Hunter Thesis Prize

*Haverford College, May 2022.*

For outstanding senior theses in economics. One of three selected as finalists for the award.


# Technical Skills

---

**Programming:** R, Python, Julia, SQL, Shell Scripting (Bash/PowerShell) Stata, Visual Basic

**Other:** Apache Hadoop, git (GitHub/GitLab), LaTeX

**Language:** English - Native